version: '3.8'

services:
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.67.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    restart: always
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

